// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID            pgtype.UUID        `json:"id"`
	ShowID        pgtype.UUID        `json:"show_id"`
	CustomerEmail string             `json:"customer_email"`
	CustomerPhone string             `json:"customer_phone"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Hall struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	TotalSeats int32              `json:"total_seats"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Movie struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	DurationMinutes int32              `json:"duration_minutes"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Seat struct {
	ID         pgtype.UUID        `json:"id"`
	HallID     pgtype.UUID        `json:"hall_id"`
	RowName    string             `json:"row_name"`
	SeatNumber int32              `json:"seat_number"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Show struct {
	ID        pgtype.UUID        `json:"id"`
	MovieID   pgtype.UUID        `json:"movie_id"`
	HallID    pgtype.UUID        `json:"hall_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Ticket struct {
	ID         pgtype.UUID        `json:"id"`
	BookingID  pgtype.UUID        `json:"booking_id"`
	ShowID     pgtype.UUID        `json:"show_id"`
	SeatID     pgtype.UUID        `json:"seat_id"`
	QrCodeHash string             `json:"qr_code_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
