// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSeatsAvailableForUpdate = `-- name: CheckSeatsAvailableForUpdate :many
SELECT t.id 
FROM tickets t
WHERE t.show_id = $1 AND t.seat_id = ANY($2::UUID[])
FOR UPDATE
`

type CheckSeatsAvailableForUpdateParams struct {
	ShowID  pgtype.UUID   `json:"show_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

// This locks the rows so no one else can book them while we check
func (q *Queries) CheckSeatsAvailableForUpdate(ctx context.Context, arg CheckSeatsAvailableForUpdateParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, checkSeatsAvailableForUpdate, arg.ShowID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (id, show_id, customer_email, customer_phone, status)
VALUES (gen_random_uuid(), $1, $2, $3, 'completed')
RETURNING id, show_id, customer_email, customer_phone, status, created_at
`

type CreateBookingParams struct {
	ShowID        pgtype.UUID `json:"show_id"`
	CustomerEmail string      `json:"customer_email"`
	CustomerPhone string      `json:"customer_phone"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.ShowID, arg.CustomerEmail, arg.CustomerPhone)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, booking_id, show_id, seat_id, qr_code_hash)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
RETURNING id, booking_id, show_id, seat_id, qr_code_hash, created_at
`

type CreateTicketParams struct {
	BookingID  pgtype.UUID `json:"booking_id"`
	ShowID     pgtype.UUID `json:"show_id"`
	SeatID     pgtype.UUID `json:"seat_id"`
	QrCodeHash string      `json:"qr_code_hash"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.BookingID,
		arg.ShowID,
		arg.SeatID,
		arg.QrCodeHash,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ShowID,
		&i.SeatID,
		&i.QrCodeHash,
		&i.CreatedAt,
	)
	return i, err
}

const getShowSeats = `-- name: GetShowSeats :many
SELECT s.id, s.hall_id, s.row_name, s.seat_number 
FROM seats s
WHERE s.hall_id = (SELECT sh.hall_id FROM shows sh WHERE sh.id = $1)
`

type GetShowSeatsRow struct {
	ID         pgtype.UUID `json:"id"`
	HallID     pgtype.UUID `json:"hall_id"`
	RowName    string      `json:"row_name"`
	SeatNumber int32       `json:"seat_number"`
}

func (q *Queries) GetShowSeats(ctx context.Context, id pgtype.UUID) ([]GetShowSeatsRow, error) {
	rows, err := q.db.Query(ctx, getShowSeats, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowSeatsRow
	for rows.Next() {
		var i GetShowSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.HallID,
			&i.RowName,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
