// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// This locks the rows so no one else can book them while we check
	CheckSeatsAvailableForUpdate(ctx context.Context, arg CheckSeatsAvailableForUpdateParams) ([]pgtype.UUID, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error)
	GetShowSeats(ctx context.Context, id pgtype.UUID) ([]GetShowSeatsRow, error)
	GetTicketsByBookingID(ctx context.Context, bookingID pgtype.UUID) ([]Ticket, error)
	UpdateTicketQRHash(ctx context.Context, arg UpdateTicketQRHashParams) error
}

var _ Querier = (*Queries)(nil)
